config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about'
  get 'homes/contact'
  
  devise_for :users
  resources :blogs, only: [:new, :create, :edit, :update, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 128 }
  validates :body, presence: true, length: { maximum: 3000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :if_admin, only: [:new, :create, :edit, :update, :destroy]

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save 
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @blogs = Blog.all.order(created_at: :desc)
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blog_path(@blog)
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to root_path
  end

  private

  def if_admin
    redirect_to root_path unless current_user.admin?
  end

  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @blogs = Blog.all.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/blogs/_form.html.erb
<%= form_with model: blog, local:true do |f| %>
  <%= render 'layouts/error', model: f.object %>
  <table class="form-table">
    <tbody>
      <tr>
        <td><%= f.text_field :title, placeholder: "タイトル" %></td>
      </tr>
      <tr>
        <td><%= f.text_area :body, placeholder: "本文" %></td>
      </tr>
    </tbody>
  </table>
  <%= f.submit '投稿・更新', class: "btn-submit" %>
<% end %>

app/views/blogs/edit.html.erb
<%= render "form", blog: @blog %>

app/views/blogs/new.html.erb
<%= render "form", blog: @blog %>

app/views/blogs/show.html.erb
<div class="article">
  <h2><%= @blog.title %></h2>
  <p class="body"><%= @blog.body %></p>
  <p class="created-at"><%= @blog.created_at.strftime('%Y/%m/%d') %></p>
  
  <div class="edit-menu">
    <% if @blog.user == current_user && current_user.admin? %>
      <%= link_to "編集", edit_blog_path(@blog), class: "edit" %>
      |
      <%= link_to "削除", blog_path(@blog), method: :delete, class: "delete" %>
    <% end %>
  </div>
</div>

app/views/homes/about.html.erb
<div class="inner">
  <h1>About me</h1>
  <h2>Work Experience</h2>
  <h3>Infratop Inc. (Intern / Mentor) 2021/8~</h3>

  <h2>Skills</h2>

  <h3>Language/Library</h3>
  <img alt="Python" src="https://img.shields.io/badge/-Python-3776AB.svg?logo=python&style=for-the-badge&logoColor=white">
  <img alt="Flask" src="https://img.shields.io/badge/Flask-000000?style=for-the-badge&logo=flask&logoColor=white">
  <img alt="Go" src="https://img.shields.io/badge/-Go-007d9c.svg?logo=go&style=for-the-badge&logoColor=white">
  <img alt="Ruby" src="https://img.shields.io/badge/Ruby-CC342D?style=for-the-badge&logo=ruby&logoColor=white" />
  <img alt="Ruby on Rails" src="https://img.shields.io/badge/Ruby_on_Rails-CC0000?style=for-the-badge&logo=ruby-on-rails&logoColor=white" />
  <img alt="C" src="https://img.shields.io/badge/-C-A8B9CC.svg?logo=c&style=for-the-badge&logoColor=black">
  <img alt="Shell Script" src="https://img.shields.io/badge/Shell_Script-121011?style=for-the-badge&logo=gnu-bash&logoColor=white" />
  <img alt="Javascript" src="https://img.shields.io/badge/Javascript-F7DF1E.svg?logo=javascript&style=for-the-badge&logoColor=black">
  <img alt="Node.js" src="https://img.shields.io/badge/Node.js-43853D?style=for-the-badge&logo=node.js&logoColor=white">
  <img alt="Vue.js" src="https://img.shields.io/badge/-Vue.js-4FC08D?style=for-the-badge&logo=vue.js&logoColor=white" />
  <img alt="Nuxt.js" src="https://img.shields.io/badge/-Nuxt.js-00C58E?style=for-the-badge&logo=nuxt.js&logoColor=white" />
  <img alt="Sass" src="https://img.shields.io/badge/-Sass-CC6699?style=for-the-badge&logo=sass&logoColor=white" />
  <img alt="Bootstrap" src="https://img.shields.io/badge/-Bootstrap-563D7C?style=for-the-badge&logo=bootstrap&logoColor=white" />

  <h3>Database</h3>
  <img alt="MySQL" src="https://img.shields.io/badge/MySQL-00000F?style=for-the-badge&logo=mysql&logoColor=white" />
  <img alt="PostgreSQL" src="https://img.shields.io/badge/PostgreSQL-316192?style=for-the-badge&logo=postgresql&logoColor=white" />
  <img alt="SQLite" src="https://img.shields.io/badge/SQLite-07405E?style=for-the-badge&logo=sqlite&logoColor=white" />

  <h3>Service/Tool</h3>
  <img alt="Amazon Cloud9" src="https://img.shields.io/badge/Amazon_Cloud9-232F3E?style=for-the-badge&logo=amazon-aws&logoColor=white" />
  <img alt="Heroku" src="https://img.shields.io/badge/-Heroku-430098?style=for-the-badge&logo=heroku&logoColor=white" />
  <img alt="Firebase" src="https://img.shields.io/badge/-Firebase-FFCA28?style=for-the-badge&logo=firebase&logoColor=black" />
  <img alt="Netlify" src="https://img.shields.io/badge/Netlify-00C7B7?style=for-the-badge&logo=netlify&logoColor=white" />
  <img alt="Git" src="https://img.shields.io/badge/-Git-F05032?style=for-the-badge&logo=git&logoColor=white" />
  <img alt="Github Actions" src="https://img.shields.io/badge/-Github_Actions-2088FF?style=for-the-badge&logo=github-actions&logoColor=white" />
</div>

app/views/homes/contact.html.erb
<div class="inner">
  <h1>Contact</h1>
  <table class="contact">
    <tbody>
      <tr>
        <th>
          <i class="far fa-envelope"></i>
          <p>Gmail</p>
        </th>
        <td>broccolingual@gmail.com</td>
      </tr>
      <tr>
        <th>
          <i class="fab fa-github"></i>
          <p>Github</p>
        </th>
        <td>
          <a href="https://github.com/broccolingual" target="_blank" rel="noopener noreferrer">broccolingual</a>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/homes/top.html.erb
<% @blogs.each do |blog| %>
  <div class="article">
    <%= link_to blog_path(blog) do %>
      <h2><%= blog.title %></h2>
      <p class="body"><%= blog.body.truncate(128) %></p>
      <p class="created-at"><%= blog.created_at.strftime('%Y/%m/%d') %></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div class="alert">
    <p>Error: </p>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>© 2020-present Broccolingual. All rights reserved. Design by Broccolingual.</p>
    <br>
    <h2>Links</h2>
    <ul>
      <% if user_signed_in? %>
        <% if current_user.admin? %>
        <li>
          <%= link_to '投稿フォーム', new_blog_path %>
        </li>
        <% end %>
        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign Up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "Log In", new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="menu">
      <ul>
        <li>
          <i class="fas fa-home"></i>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <i class="fas fa-user-friends"></i>
          <%= link_to "About me", homes_about_path %>
        </li>
        <li>
          <i class="far fa-address-card"></i>
          <%= link_to "Contact", homes_contact_path %>
        </li>
      </ul>
    </div>
    <div class="logo">
      <h2>Broccolingual</h2>
    </div>
  </div>
</header>
<% if user_signed_in? && current_user.admin? %>
  <div class="admin-notice">
    <div class="container">
      <p>Adminアカウントでログイン中</p>
      <div class="login-menu">
        <ul>
          <li>
            <%= link_to '投稿フォーム', new_blog_path %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="profile">
  <div class="thumb">
    <%= image_tag 'me.jpg' %>
  </div>
  <h2 class="name">
    Broccolingual
  </h2>
  <p class="info">
    Developer of a Discord Bot, Frontend(Nuxt.js, Ruby on Rails), Heroku, Firebase
  </p>
  <p class="organization">
    <i class="far fa-building"></i>
    Infratop inc. (intern), Student
  </p>
  <p class="location">
    <i class="fas fa-map-marker-alt"></i>
    Osaka, Japan
  </p>
  <div class="links">
    <ul>
      <li>
        <a href="https://qiita.com/Broccolingual" target="_blank" rel="noopener noreferrer">
          <i class="fas fa-book"></i>
        </a>
      </li>
      <li>
        <a href="https://github.com/broccolingual" target="_blank" rel="noopener noreferrer">
          <i class="fab fa-github"></i>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Broccolingual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <div class="container">
        <div class="sidebar">
          <%= render "layouts/sidebar" %>
        </div>
        <div class="contents">
          <%= yield %>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>